### ISSUE TITLE
Tab expansion is broken.

### ISSUE THREAD

**Issue by vemec** [emmetio/emmet-atom#108]
I had a clean install of Atom, then installed emmet, and now the tab expansion is not working. When I use the keystroke shift-cmd-E it works every time.

gif example
![example](https://cloud.githubusercontent.com/assets/839090/3530311/3d4371dc-07a3-11e4-999e-8bf3af166984.gif)
##

**Comment by silvenon** [comment]
You can now easily enable tab for your favorite language, read [this](https://github.com/emmetio/emmet-atom#tab-key) for more info. This works for me now.

**Comment by freqn** [comment]
Not working for me. Fresh install on Ubuntu 14.04 LTS

**Comment by riebschlager** [comment]
Thanks @silvenon, that resolved this issue for me.

In my case the Angular package had changed the grammar of the editor to "text html angular" in an HTML file with some Angular syntax. Adding that grammar in the keymap fixed it.

**Comment by chrissm79** [comment]
Life saver @silvenon, thank you for that!

**Comment by jesusjjf** [comment]
Im having issues now when trying to expand snippets. 
They will only expand with `enter` not tab anymore.

**Comment by jbotos** [comment]
Atom > Open Your Keymap

Paste this in:

'atom-text-editor:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'

Worked for me after restart.

**Comment by kandros** [comment]
@jbotos 's response looks good (beware the second line must be indented)

Can we close this please?

**Comment by yigitozkavci** [comment]
Thanks @jbotos that works like a charm.

**Comment by DarrenBell** [comment]
@jbotos Thanks this was truly frustrating and made me continue on with ST3 until I found this.

**Comment by nsrau** [comment]
@jbotos thanks

**Comment by sergeche** [comment]
Just a FYI for all frustrated about Emmet’s Tab handler in Atom compared to Sublime Text and possible workarounds.

The main reason why ST tab handler works better that Atom’s is how editor matches current scope for given key (Tab in our case). In ST you can use very deep scope selectors (down till token right before caret) but in Atom only root scope is available. For example, it ST you can use selector like `text.html.php string` so Tab handler will work if caret is inside PHP string and won’t if caret is somewhere else. This is good since Emmet’s "take any string and transform it into something" behavior: we can clearly mark source code regions where user would likely have Emmet to work *instead of native snippets*.

In Atom such deep selectors are not available: you can only tell it to override given key entirely for current document. That’s why I can’t (easily) enable Tab handler for all HTML-compatible syntaxes (like PHP, handlebars etc.): it’s a breaking change for many users who prefer to use native Atom snippets and expand them by Tab. Emmet will completely override Tab handler for such syntaxes and you won’t be able to complete native snippets with Tab key.

If you don’t use native snippets or prefer complete suggestions with Enter key (like me), you can perfectly use @jbotos solution and use Emmet in every possible editor syntax. Otherwise, you should carefully pick scope selectors for every syntax you want Emmet to work [as described here](https://github.com/emmetio/emmet-atom#tab-key).

**Comment by yahyazini** [comment]
@jbotos Thanks, it works like a charm!

**Comment by istiu** [comment]
@jbotos Saved my day! :D

**Comment by farskid** [comment]
@jbotos Thanks. First I tried `'atom-text-editor[data-grammer="text html basic php volt"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'` But that did not work. Then I came across your answer and it worked form me. I'm using Atom on ubuntu 14.04 LTS

**Comment by azharijelek** [comment]
Thank you @jbotos . works like a charm

**Comment by ecfaria** [comment]
Thanks you @jbotos! I was going crazy with this problem!

**Comment by edubasabe** [comment]
Thanks @jbotos that work for me:

'atom-text-editor':'not([mini])'
'tab': 'emmet:expand-abbreviation-with-tab'

**Comment by letanure** [comment]
Thanks @jbotos that work for me too:

file `keymap.cson` on (Atom > keymap)
```cson
'atom-text-editor:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by louisnovick** [comment]
Disabling snippets core package did it for me.

**Comment by andrebrandaoo** [comment]
Thanks @jbotos that work for me o/

**Comment by Dajust** [comment]
Thanks @jbotos.  This is awesome!

If you're on linux and you're a novice like me, and if you installed atom via the command palette `⌘-⇧-p`, then locating Keymap might be a bit trickery.

First your Atom directory is hidden in your root folder.
From your root directory, do `CTR` + `H` to see all hidden items. Then follow this path to locate the `.emmet.cson` file: .atom  > packages > emmet > Keymap

**Comment by luizpaulo165** [comment]
@jbotos Thanks! It worked! =D

**Comment by HendrikOB** [comment]
'atom-text-editor:not([mini])':
  'ctrl-q': 'emmet:expand-abbreviation'

another solution to avoid conflicts with keymap.

**Comment by rflmyk** [comment]
@jbotos Thanks for share!

**Comment by JakobeAnthony666** [comment]
hey dudes try just doing head then tab after you have added the code at end of key maps!
