### ISSUE TITLE
Expand abbreviation problem with single tags.

### ISSUE THREAD

**Issue by rustedwolf** [emmetio/emmet-atom#227]
Hello, I've tried to expand simple "br" tag and it gave me:
```html
<br></br>
```
expected:
```html
<br/>
```
or at least HTML5 version
```html
<br>
```
same thing happens with input tag.

**Comment by silvenon** [comment]
Is your grammar set to HTML or some templating language which has HTML, such as PHP?

**Comment by rustedwolf** [comment]
Yes, Twig templating language.

**Comment by silvenon** [comment]
Try creating a `~/emmet/snippets.json` file with the following content:

```json
{
  "php": {
    "extends": "html"
  },
  "twig": {
    "extends": "php"
  }
}
```

This will tell Emmet that Twig is derived from PHP and that PHP is derived from HTML. Then restart Atom.

**Comment by rustedwolf** [comment]
Well, I've tried ```/home/user/emmet/snippets.json``` and ```/home/user/.atom/packages/emmet/snippets.json```, maybe I'm assuming wrong ```~/``` directory?

**Comment by rustedwolf** [comment]
Update: 
I've noticed the ```emmet:expand-abbreviation-with-tab``` as a alternative expand command. Well, that worked. 
But it feels kinda weird, I though ```emmet:expand-abbreviation``` add TAB calles command should return the same result.

**Comment by silvenon** [comment]
The `/home/user/emmet/snippets.json` is the correct one. That's where you should be adding new snippets if you're using Emmet.

Oh right, you also had to add your language as described [here](https://github.com/emmetio/emmet-atom#tab-key).

No, because `emmet:expand-abbreviation` does extra things, like fuzzy matching etc.

**Comment by rustedwolf** [comment]
Well, when instructions state that to expand an abbreviation you need to press ```Tab``` or ```Ctrl+E``` its assumed that they are going to do the same functionality and produce the same results.
I understood, action called with ```Ctrl+E``` needs additional setup, but action called with```Tab``` does not.
So that's the benefit of using ```Ctrl+E``` called command over the one called with a ```Tab``` key? I'm getting confused.

**Comment by sergeche** [comment]
Tab key works for limited scopes to not interfere with default snippets: https://github.com/emmetio/emmet-atom#tab-key

**Comment by silvenon** [comment]
I'm not sure I understood you correctly. It's <kbd>ctrl</kbd> + <kbd>e</kbd> that doesn't require additional setup. <kbd>tab</kbd> does because it overrides Atom's snippet expansion shortcut, so you might not want it everywhere. For <kbd>tab</kbd> to run `emmet:expand-abbreviation` in Swig grammar (for example) you need to add it to your `keymaps.cson`.

**Comment by rustedwolf** [comment]
Nope, surprisingly the <kbd>tab</kbd> key works without snippets setup. 
The result of ```br``` abbreviation is ```<br>```.
It's the <kbd>ctrl</kbd>+<kbd>e</kbd> I was having problems.

**Comment by silvenon** [comment]
That makes no sense :stuck_out_tongue: But ok.

**Comment by rustedwolf** [comment]
Ok, closing the issue. :D
