### ISSUE TITLE
Tab Completion Error

### ISSUE THREAD

**Issue by vinkla** [emmetio/emmet-atom#334]
After installing Emmet in Atom the tab completion stops working for the autocomplete-plus package. When I disable this package it works again and stops when I enable it again.

**Comment by sergeche** [comment]
Emmet overrides Tab key for expanding abbreviations. You can use Enter key to complete standard snippets

**Comment by vinkla** [comment]
So my option is to stop using the tab key for autocomplete-plus? Can't they work together?

**Comment by sergeche** [comment]
Right now they can’t work together. It requires additional integration with autocomplete-plus

**Comment by vinkla** [comment]
Aah okay, I see. Thanks for sharing.

**Comment by ProLoser** [comment]
I have this problem too, and in css it turns `disp` + tab into `disp: ;` which is useless. I think at the very least emmet autocompletion should be removed from CSS. And if there is no way to set a lower priority on emmet you should have an ability to disable emmet's autocompletion so that you have to opt-in using a specific shortcut (such as `CTRL+E` or `META+E`) instead of the far more global, common, and heavily used autocomplete behavior. OR make the emmet expansion an autocompletion option so that we can get a small preview snippet of what emmet will create and also give us a way to opt out of it (by selecting a different autocompletion) using a UI paradigm we're already familiar with instead of upsetting the existing standardized UI and giving us more shortcuts to memorize.

**Comment by vinkla** [comment]
This issue is fairly old, closing it due to inactivity.
