### ISSUE TITLE
Tab Stopped working for initializing classes inside an element

### ISSUE THREAD

**Issue by moeshu** [emmetio/emmet-atom#515]
when i do 
div.class> 
then press tab it doesn't complete but it used to do that

**Comment by jyoseph** [comment]
I had a similar issue, turns out that only certain syntaxes are supported.

> Currently, Emmet expands abbreviations by Tab key only for HTML, CSS, Sass/SCSS and LESS syntaxes. Tab handler scope is limited because it overrides default snippets.

If you want to make Emmet expand abbreviations with Tab key for other syntaxes, you can do the following:

> Use Open Your Keymap menu item to open your custom keymap.cson file.
> Add the following section into it:
>
> 'atom-text-editor[data-grammar="YOUR GRAMMAR HERE"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
>
> Replace YOUR GRAMMAR HERE with actual grammar attribute value. The easiest way to get grammar name of currently opened editor is to open DevTools and find corresponding <atom-text-editor> element: it will contain data-grammar attribute with value you need. For example, for HTML syntax it’s a text html basic.

For me, it looked like this (to add support for cfml):

> 'atom-text-editor[data-grammar="text html cfml"]:not([mini])':
>    'tab': 'emmet:expand-abbreviation-with-tab'

Might not be your exact issue, but thought it worth mentioning.
