### ISSUE TITLE
Unable to override textarea snippet

### ISSUE THREAD

**Issue by LeaVerou** [emmetio/emmet-atom#618]
Hi all,

Thank you for this project.
I've been trying to override the HTML textarea snippet (per the recommendation in emmetio/emmet#582). I created a `~/emmet/snippets.json` file, and put this in it:

```json
{
	"html": {
		"textarea": null
	}
}
```

then restarted Atom. However `textarea`[Tab] still autocompletes to all the predefined attributes, and not just `<textarea></textarea>`. Any ideas?

Thanks in advance!

**Comment by sergeche** [comment]
Hi Lea,
this plugin is very outdated and I’m in the middle of switching all Emmet plugins into a new Emmet implementation. 

For this plugin, you should follow snippets format from `legacy` branch: https://github.com/emmetio/emmet/blob/legacy/lib/snippets.json

In your case, it should look like this:

```json
{
  "html": {
    "abbreviations": {
      "textarea": "<textarea name=\"\">"
    }
  }
}
```

You should restart Atom in order to update snippets

**Comment by LeaVerou** [comment]
That worked, thank you so much! Closing this now.
