### ISSUE TITLE
html element false positives

### ISSUE THREAD

**Issue by cameronmcefee** [emmetio/emmet-atom#69]
Given: `div.button`

Emmet expands to `div.<button name="button"></button>`

Or `span.help`

Expands to:

```
span.hel<p>

</p>
```

**Comment by johnwaweru** [comment]
There are a couple of plugins taking precedence over emmet. I found it best to override the keybindings as follows:
Access your keymap file under file->keymap
Paste the following code at the bottom of the page so you that can use shift-space combination to expand your code:

```
'atom-text-editor:not([mini])':
  'shift-space': 'emmet:expand-abbreviation'
```

Change shift-space to a combination of your choice.

**Comment by AnthonyMichaelc** [comment]
The last solution @johnwaweru recommended seemed to fix my issue. Was coming from ST3 back to Atom and was enjoying everything until the tab expand stopped working today. Now that fix seems to expand again.

**Comment by jcmarchi** [comment]
How can I completely change the behavior of the 'shift-space' in Emmet to something less obnoxious as, let's say, 'ctrl-shift-space'?

I want 'shift-space' do simply do a "space", nothing else...

**Comment by johnwaweru** [comment]
The same instructions I recommended above still apply now just change the key binding to whatever you prefer. In this case: 

```
'atom-text-editor:not([mini])':
  'ctrl-shift-space': 'emmet:expand-abbreviation'
```

@jcmarchi What's obnoxious to you might be another's preference so what you need to do is learn how to use the Atom Key Binding resolver as follows:

Use `ctrl + .` to get into the resolver and `ctrl + .` again to get out of the resolver. 

While in the resolver, if you press the combination of keys that are giving you a problem you'll see what the key binding is being applied to and this will guide you as to how your key bindings are being applied (Look at the bottom left of your editor to see the 'Key Binding Resolver' text)

Always be sure to get out of the keybinding resolver by using `ctr + .` otherwise you won't be able to do much else with your keyboard on Atom.

**Comment by jcmarchi** [comment]
Hello John,

Thank you for your answer. In fact, the "*obnoxious*" part was exactly
trying to use the Key Bind Resolver for "shift+space" and, for some reason,
find it not working... (something was wrong, surely).

I've then implemented a workaround that, somehow, uncovered the location of
the KeyBind from Emmet, allowing me to fix it as it should be. The
workaround was the following:

In the *init.coffee* file, I added the following function:
*"atom.commands.add 'atom-text-editor',*
*   'custom:insert-space': ->*
*      atom.workspace.getActiveTextEditor()?.insertText(' ')"*

Then, on *keymap.cson* I forced the Key Bind by adding in the section '
atom-text-editor:not([mini])' the following :
*# Change EMMET's shift-space behavior to be ctrl-shift-space.*
*   'ctrl-shift-space': 'emmet:expand-abbreviation'*
*   'shift-space': 'custom:insert-space'*

After done that and restarted Atom the Key Resolver was able to pin point
the Emmet file where the KeyBind was, then I fixed it as I pleased and
removed the changes above. Weird, right?

In anyhow, thank you very much for your reply. I help me by reassuring I
was doing the right thing. ;)

Regards,

Julio Marchi ©
Technology Executive & Entrepreneur
(586) 996-3939
jcmarchi@gmail.com

This e-mail and any attachments may contain information which is
confidential, proprietary, privileged or otherwise protected by law. The
information is solely intended for the named addressee (or a person
responsible for delivering it to the addressee). If you are not the
intended recipient of this message, you are not authorized to read, print,
retain, copy or disseminate this message or any part of it. If you have
received this e-mail in error, please notify the sender immediately by
return e-mail and delete it from your computer.​
